library(car)
alphabets$Subject = factor(alphabets$Subject)
summary(alphabets)
library(plyr)
ddply(alphabets, ~ Alphabet,function(data) summary(data$WPM))
shapiro.test(alphabets[alphabets$Alphabet == "EdgeWrite",]$WPM)
shapiro.test(alphabets[alphabets$Alphabet == "Graffiti",]$WPM)
shapiro.test(alphabets[alphabets$Alphabet == "Unistrokes",]$WPM)
awpm = aov(Alphabet ~ WPM, data=alphabets)
shapiro.test(residuals(awpm))
leveneTest(WPM ~ Alphabet, data=alphabets, center=median)
anova(aov(WPM ~ Alphabet, data=alphabets))
awpm = aov(WPM ~ Alphabet, data=alphabets)
library(multcomp)
alphabets$Alphabet = as.numeric(alphabets$Alphabet)
alphabets$WPM = as.numeric(alphabets$WPM)
is.factor(alphabets$Alphabet)
summary(glht((aov(WPM ~ Alphabet, data=alphabets)), mcp(Alphabet="Tukey")), test=adjusted(type="holm")) 
kruskal_test(WPM ~ Alphabet, data=alphabets, distribution="asymptotic")
uni.edg = wilcox.test(alphabets[alphabets$Alphabet == "Unistrokes",]$WPM, alphabets[alphabets$Alphabet == "Edgewire",]$WPM, exact=FALSE)
uni.graf = wilcox.test(alphabets[alphabets$Alphabet == "Unistrokes",]$WPM, alphabets[alphabets$Alphabet == "Grafitti",]$WPM, exact=FALSE)
graf.edg = wilcox.test(alphabets[alphabets$Alphabet == "Grafitti",]$WPM, alphabets[alphabets$Alphabet == "Edgewire",]$WPM, exact=FALSE)
p.adjust(c(uni.edg$p.value, uni.graf$p.value, graf.edg$p.value), method="holm")